package hu.bme.cah.api.cardsagainsthumanityapi.log.domain;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.time.LocalDateTime;

/**
 * Entity reperesting a log
 */
@Data
@Entity
public class Log {
    /**
     * Log's id
     */
    private Long id;

    /**
     * Log constructor
     */
    public Log() {

    }

    /**
     * Id setter
     * @param id id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Id setter
     * @return id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long getId() {
        return id;
    }

    /**
     * The log's text
     */
    private String log;

    /**
     * Loglevel
     */
    private LogLevel level;

    /**
     * Log's date
     */
    private LocalDateTime date;

    /**
     * Getters and Setters
     */
    public String getLog() {
        return log;
    }

    public void setLog(String log) {
        this.log = log;
    }

    public LogLevel getLevel() {
        return level;
    }

    public void setLevel(LogLevel level) {
        this.level = level;
    }

    public LocalDateTime getDate() {
        return date;
    }

    public void setDate(LocalDateTime date) {
        this.date = date;
    }

    /**
     * Log constructor
     * @param id id (autogenerated)
     * @param log text
     * @param level logLevel
     * @param date date
     */
    public Log(Long id, String log, LogLevel level, LocalDateTime date) {
        this.id = id;
        this.log = log;
        this.level = level;
        this.date = date;
    }
}
